import { DashboardData } from '@/types/dashboard';

const escapeHTML = (value: string | number) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char] ?? char);
const formatNumber = (value: number) => value.toLocaleString('pt-BR');
const formatImpressions = (value: number) => value >= 1000 ? `${(value / 1000).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} mil` : formatNumber(value);

export function generateHTMLContent(data: DashboardData): string {
  const ga4PageRows = data.ga4.topPages.map((page, index) => `<tr><td>${index + 1}. ${escapeHTML(page.title)}</td><td class="number">${page.views}</td></tr>`).join('');
  const gscQueryRows = data.gsc.queries.map((item) => `<tr><td>${escapeHTML(item.query)}</td><td class="number">${item.clicks ?? '—'}</td><td class="number">${item.impressions}</td><td class="number">${item.position.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</td></tr>`).join('');
  const gscContentRows = data.gsc.contents.map((item) => `<tr><td>${escapeHTML(item.title)}</td><td class="number">${item.clicks}</td><td class="number">${item.impressions}</td></tr>`).join('');
  const gscDailyRows = data.gsc.dailyMetrics.map((item) => `<tr><td>${escapeHTML(item.date)}</td><td class="number">${item.clicks}</td><td class="number">${formatNumber(item.impressions)}</td><td class="number">${item.ctr.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}%</td><td class="number">${item.position.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</td></tr>`).join('');
  const activeWindows = [[`Último 1 dia`, data.ga4.activeUsers1d], ['Últimos 7 dias', data.ga4.activeUsers7d], ['Últimos 30 dias', data.ga4.activeUsers30d]].filter(([, value]) => typeof value === 'number').map(([label, value]) => `<div class="metric"><span>${label}</span><strong>${value}</strong><small>usuários ativos únicos</small></div>`).join('');
  const rankItems = [['Palavras rastreadas', `${data.ubersuggest.trackedKeywords}/${data.ubersuggest.totalTrackedKeywords}`], ['Em alta', data.ubersuggest.keywordsUp], ['Em baixa', data.ubersuggest.keywordsDown], ['Sem alteração', data.ubersuggest.keywordsUnchanged], ['Top 3', data.ubersuggest.top3], ['Top 10', data.ubersuggest.top10], ['Top 100', data.ubersuggest.top100], ['Não posicionadas', data.ubersuggest.notRanked]].map(([label, value]) => `<div class="metric"><span>${label}</span><strong>${value}</strong></div>`).join('');

  return `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Dashboard SEO — ${escapeHTML(data.company)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f2f7;color:#253842;font-family:Arial,sans-serif;line-height:1.5}.container{max-width:1160px;margin:auto;padding:30px 18px}.hero{padding:32px;border-radius:28px;background:linear-gradient(110deg,#183347,#274d64,#895838);color:#fff}.hero h1{margin:14px 0 8px;font-size:42px}.badge{display:inline-block;border:1px solid #ffffff35;border-radius:999px;padding:6px 10px;font-size:12px;font-weight:700;letter-spacing:.06em}.kpis,.grid{display:grid;gap:14px}.kpis{grid-template-columns:repeat(4,1fr);margin-top:23px}.card,.metric{background:#fff;border:1px solid #dbe5ec;border-radius:16px;padding:18px;box-shadow:0 4px 15px #203c500c}.card{margin-top:22px}.card h2{margin:0 0 7px;color:#203c50;font-size:26px}.card h3{color:#203c50;font-size:17px;margin:22px 0 10px}.sub{margin:0;color:#64727b;font-size:14px}.metric span{display:block;color:#68757d;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.metric strong{display:block;color:#203c50;font-size:28px;margin-top:5px}.metric small{color:#68757d;font-size:12px}.kpis .metric{background:#ffffff12;border-color:#ffffff32}.kpis .metric span,.kpis .metric strong{color:#fff}.grid{grid-template-columns:repeat(3,1fr)}.takeaway{border-top:4px solid #203c50;background:#fff;border-radius:16px;padding:18px;margin-top:18px;box-shadow:0 4px 15px #203c500c}.takeaway b{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:#203c50}.takeaway b:before{content:'•';color:#ff6737;margin-right:8px;font-size:20px}.takeaway p{margin:8px 0 0;color:#203c50;font-weight:700;font-size:16px}.note{border-left:4px solid #ff6737;background:#fff5f0;padding:14px;margin-top:16px;font-size:14px;color:#62351f}table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;border-bottom:1px solid #dbe5ec;padding:9px 7px;color:#65717a;font-size:11px;text-transform:uppercase}td{padding:10px 7px;border-bottom:1px solid #eef1f3;vertical-align:top}.number{text-align:right;font-weight:700;color:#203c50}.red{color:#b43737}.ai{background:#203c50;color:#fff;border-radius:16px;padding:19px;margin:-18px -18px 20px}.ai h2{color:#fff}.ai p{color:#e0e9ee}.list{padding-left:20px}.list li{padding:5px 0}@media(max-width:720px){.kpis,.grid{grid-template-columns:1fr 1fr}.hero h1{font-size:34px}.container{padding:18px 12px}} </style></head><body><main class="container">
<header class="hero"><span class="badge">JD · RELATÓRIO EXECUTIVO · SEO &amp; IA</span><h1>${escapeHTML(data.company)}</h1><p>Últimos 7 dias · ${escapeHTML(data.period.startDate)} a ${escapeHTML(data.period.endDate)}</p><div class="kpis"><div class="metric"><span>Usuários ativos</span><strong>${data.ga4.activeUsers}</strong></div><div class="metric"><span>Cliques orgânicos</span><strong>${data.gsc.clicks}</strong></div><div class="metric"><span>Impressões</span><strong>${formatImpressions(data.gsc.impressions)}</strong></div><div class="metric"><span>Eventos principais</span><strong>${data.ga4.conversions}</strong></div></div></header>
<section class="card"><h2>Desempenho do Site — Google Analytics 4</h2><p class="sub">Canal: Organic Search.</p><div class="grid" style="margin-top:18px"><div class="metric"><span>Usuários ativos</span><strong>${data.ga4.activeUsers}</strong></div><div class="metric"><span>Novos usuários</span><strong>${data.ga4.newUsers}</strong></div><div class="metric"><span>Visualizações</span><strong>${data.ga4.pageViews}</strong></div><div class="metric"><span>Tempo médio</span><strong>${escapeHTML(data.ga4.engagementTime)}</strong></div><div class="metric"><span>Eventos principais</span><strong>${data.ga4.conversions}</strong></div></div><div class="takeaway"><b>Leitura executiva</b><p>O recorte registra ${data.ga4.activeUsers} usuários ativos, ${data.ga4.pageViews} visualizações e ${escapeHTML(data.ga4.engagementTime)} de engajamento médio. A coleta não trouxe detalhamento diário, dispositivos, sistema operacional ou localidades.</p></div><h3>Usuários ativos por janela</h3><div class="grid">${activeWindows}</div><h3>Evento principal</h3><div class="note"><b>${escapeHTML(data.ga4.conversionEvent.name)}</b> · ${data.ga4.conversionEvent.count} clique rastreado. A coleta não informa a página de origem; não tratar automaticamente como lead ou venda.</div><h3>Principais páginas por visualizações</h3><table><thead><tr><th>Página</th><th class="number">Visualizações</th></tr></thead><tbody>${ga4PageRows}</tbody></table></section>
<section class="card"><h2>Visibilidade no Google — Search Console</h2><p class="sub">Comparação com ${escapeHTML(data.previousPeriod?.startDate ?? 'período anterior')} a ${escapeHTML(data.previousPeriod?.endDate ?? '')}.</p><div class="grid" style="margin-top:18px"><div class="metric"><span>Cliques</span><strong>${data.gsc.clicks}</strong><small class="red">${data.gsc.clicksChange}</small></div><div class="metric"><span>Impressões</span><strong>${formatImpressions(data.gsc.impressions)}</strong><small class="red">${data.gsc.impressionsChange}</small></div><div class="metric"><span>CTR</span><strong>${data.gsc.ctr.toLocaleString('pt-BR',{minimumFractionDigits:2})}%</strong><small class="red">${data.gsc.ctrChange}</small></div><div class="metric"><span>Posição média</span><strong>${data.gsc.avgPosition.toLocaleString('pt-BR',{minimumFractionDigits:2})}</strong><small class="red">${data.gsc.avgPositionChange}</small></div></div><div class="takeaway"><b>Leitura executiva</b><p>A coleta registrou ${data.gsc.clicks} cliques, ${formatNumber(data.gsc.impressions)} impressões, CTR de ${data.gsc.ctr.toLocaleString('pt-BR',{minimumFractionDigits:2})}% e posição média de ${data.gsc.avgPosition.toLocaleString('pt-BR',{minimumFractionDigits:2})}. Os quatro indicadores variaram negativamente frente ao período anterior.</p></div><h3>Desempenho diário retornado</h3><p class="sub">A fonte retornou dados somente para 02/09 a 06/09; dias sem retorno não foram preenchidos.</p><table><thead><tr><th>Data</th><th class="number">Cliques</th><th class="number">Impressões</th><th class="number">CTR</th><th class="number">Posição</th></tr></thead><tbody>${gscDailyRows}</tbody></table><h3>Consultas principais</h3><table><thead><tr><th>Consulta</th><th class="number">Cliques</th><th class="number">Impressões</th><th class="number">Posição</th></tr></thead><tbody>${gscQueryRows}</tbody></table><h3>Conteúdos principais</h3><table><thead><tr><th>Conteúdo</th><th class="number">Cliques</th><th class="number">Impressões</th></tr></thead><tbody>${gscContentRows}</tbody></table></section>
<section class="card"><h2>Visibilidade, Autoridade e IA — Ubersuggest</h2><p class="sub">Localização Brasil / português · posição média disponível em ${escapeHTML(data.ubersuggest.evolutionDate)}.</p><div class="grid" style="margin-top:18px"><div class="metric"><span>Palavras-chave orgânicas</span><strong>${data.ubersuggest.organicKeywords}</strong></div><div class="metric"><span>Domain Authority</span><strong>${data.ubersuggest.domainAuthority}</strong></div><div class="metric"><span>Backlinks</span><strong>${data.ubersuggest.backlinks}</strong></div><div class="metric"><span>Posição média disponível</span><strong>${data.ubersuggest.trackedAveragePosition}</strong></div></div><h3>Palavras-chave rastreadas</h3><div class="grid">${rankItems}</div><div class="takeaway"><b>Leitura executiva</b><p>As ${data.ubersuggest.trackedKeywords} palavras rastreadas ficaram sem alteração. O relatório não forneceu comparativo anterior além da posição média disponível.</p></div><h3>Como a IA vê seu site</h3><div class="grid"><div class="metric"><span>Visibilidade da marca</span><strong>${data.ubersuggest.aiVisibility.brandVisibility}%</strong></div><div class="metric"><span>Share of voice</span><strong>${data.ubersuggest.aiVisibility.shareOfVoice}%</strong></div><div class="metric"><span>Menções à marca</span><strong>${data.ubersuggest.aiVisibility.mentions}</strong></div><div class="metric"><span>Sentimento geral</span><strong>${escapeHTML(data.ubersuggest.aiVisibility.sentiment)}</strong></div><div class="metric"><span>Visibilidade ChatGPT/OpenAI</span><strong>${data.ubersuggest.aiVisibility.chatgptVisibility}%</strong></div><div class="metric"><span>Share of voice ChatGPT/OpenAI</span><strong>${data.ubersuggest.aiVisibility.chatgptShareOfVoice}%</strong></div><div class="metric"><span>Sentimento ChatGPT/OpenAI</span><strong>${escapeHTML(data.ubersuggest.aiVisibility.chatgptSentiment)}</strong></div></div><div class="note">Não foram incluídos dados de tráfego pago, palavras-chave pagas ou tráfego orgânico estimado nesta coleta.</div></section>
<section class="card"><h2>Plano de ação prioritário</h2><ol class="list"><li>Revisar as páginas e os conteúdos listados no Search Console, priorizando títulos, meta descriptions, CTAs e links internos.</li><li>Padronizar a mensuração entre cliques em WhatsApp, conversa iniciada, lead qualificado, orçamento e serviço concluído.</li><li>Revisar os termos rastreados no Ubersuggest e as páginas de destino, priorizando intenção local e comercial.</li></ol><div class="note">Os dados foram mantidos separados por fonte. A ausência de dados de IA generativa no prompt não é exibida como zero nem como estimativa.</div></section>
</main></body></html>`;
}

export function downloadHTML(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
