// Estilo JD: blocos executivos claros, com azul #203c50 para hierarquia e laranja #ff6737 para métricas prioritárias.
import { Eye, Mail, TrendingUp, Users, Zap } from 'lucide-react';
import KPICard from './KPICard';
import { DashboardData } from '@/types/dashboard';

interface GA4SectionProps { data: DashboardData['ga4']; }

export default function GA4Section({ data }: GA4SectionProps) {
  const hasActiveUserWindows = [data.activeUsers1d, data.activeUsers7d, data.activeUsers30d].some((value) => typeof value === 'number');
  return <section className="border-b border-gray-200 py-12"><div className="container">
    <div className="mb-8"><h2 className="section-title mb-1">Desempenho do Site — Google Analytics 4</h2><p className="text-sm text-gray-600">Fonte oficial para usuários, comportamento, páginas e eventos principais no canal Organic Search.</p></div>
    <div className="mb-8 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-5"><KPICard label="Usuários Ativos" value={data.activeUsers} icon={<Users />} /><KPICard label="Novos Usuários" value={data.newUsers} icon={<Users />} /><KPICard label="Tempo Médio" value={data.engagementTime} icon={<Zap />} /><KPICard label="Visualizações" value={data.pageViews} icon={<Eye />} /><KPICard label="Eventos Principais" value={data.conversions} icon={<TrendingUp />} /></div>
    <div className="executive-takeaway mb-8"><p className="executive-takeaway-label">Leitura executiva</p><p className="text-lg font-semibold leading-relaxed text-[#203c50]">O recorte registrou 46 usuários ativos, 53 visualizações e tempo médio de engajamento de 56 segundos. A coleta não trouxe detalhamento diário, dispositivos, sistema operacional ou localidades.</p></div>
    {hasActiveUserWindows && <div className="card-premium mb-8"><h3 className="section-subtitle">Usuários Ativos por Janela</h3><div className="grid grid-cols-1 gap-3 md:grid-cols-3">{typeof data.activeUsers1d === 'number' && <div className="rounded-lg border border-[#dfe6ea] bg-white p-4 text-center"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Último 1 dia</p><p className="mt-2 text-3xl font-bold text-[#203c50]">{data.activeUsers1d}</p><p className="mt-1 text-xs text-gray-500">usuários ativos únicos</p></div>}{typeof data.activeUsers7d === 'number' && <div className="rounded-lg border border-[#dfe6ea] bg-white p-4 text-center"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Últimos 7 dias</p><p className="mt-2 text-3xl font-bold text-[#203c50]">{data.activeUsers7d}</p><p className="mt-1 text-xs text-gray-500">usuários ativos únicos</p></div>}{typeof data.activeUsers30d === 'number' && <div className="rounded-lg border border-[#dfe6ea] bg-white p-4 text-center"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Últimos 30 dias</p><p className="mt-2 text-3xl font-bold text-[#203c50]">{data.activeUsers30d}</p><p className="mt-1 text-xs text-gray-500">usuários ativos únicos</p></div>}</div></div>}
    <div className="card-premium mb-8 border border-[#dbe5ec] bg-white"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#203c50] p-3 text-white"><Mail className="h-5 w-5" /></div><div><h3 className="section-subtitle mb-1">Evento principal</h3><p className="text-3xl font-bold text-[#203c50]">{data.conversionEvent.count}</p><p className="mt-1 text-sm font-semibold text-[#ff6737]">{data.conversionEvent.name}</p></div></div><p className="mt-5 rounded-lg border border-orange-200 bg-[#fff5f0] p-4 text-sm leading-relaxed text-[#70321d]"><strong>Nota de mensuração:</strong> o evento registra uma interação de clique. A coleta não informa a página de origem do evento, e o resultado não deve ser tratado automaticamente como lead ou venda.</p></div>
    <div className="card-premium"><h3 className="section-subtitle">Principais Páginas por Visualizações</h3><div className="overflow-x-auto"><table className="w-full min-w-[570px] text-left text-sm"><thead className="border-b border-gray-200 text-xs uppercase tracking-wide text-gray-500"><tr><th className="pb-3 pr-4 font-semibold">Página</th><th className="pb-3 text-right font-semibold">Visualizações</th></tr></thead><tbody>{data.topPages.map((page, index) => <tr key={page.title} className="border-b border-gray-100 last:border-0"><td className="py-3 pr-4 font-medium text-[#203c50]"><span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-[#fff0eb] text-xs font-bold text-[#ff6737]">{index + 1}</span>{page.title}</td><td className="py-3 text-right text-lg font-bold text-[#203c50]">{page.views}</td></tr>)}</tbody></table></div></div>
  </div></section>;
}
