// Estilo JD: dados do Search Console com comparativos claros, gráficos de evidência e azul #203c50 como estrutura visual.
import { BarChart3, Search } from 'lucide-react';
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import KPICard from './KPICard';
import { DashboardData } from '@/types/dashboard';

interface GSCSectionProps { data: DashboardData['gsc']; }
const formatImpressions = (value: number) => value >= 1000 ? `${(value / 1000).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} mil` : value.toLocaleString('pt-BR');

export default function GSCSection({ data }: GSCSectionProps) {
  return <section className="border-b border-gray-200 py-12"><div className="container">
    <div className="mb-8"><h2 className="section-title mb-1">Visibilidade no Google — Search Console</h2><p className="text-sm text-gray-600">Propriedade sc-domain:desentupidorajd.com.br · comparação com 26/08 a 01/09/2026.</p></div>
    <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4"><KPICard label="Cliques Orgânicos" value={data.clicks} icon={<Search />} /><KPICard label="Impressões" value={formatImpressions(data.impressions)} icon={<BarChart3 />} /><KPICard label="CTR Médio" value={`${data.ctr.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}%`} /><KPICard label="Posição Média" value={data.avgPosition.toLocaleString('pt-BR', { minimumFractionDigits: 2 })} /></div>
    <div className="mb-8 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-xs font-semibold text-gray-600">Variação de cliques</p><p className="mt-2 text-2xl font-bold text-red-700">{data.clicksChange}</p><p className="mt-1 text-xs text-gray-500">vs. período anterior</p></div><div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-xs font-semibold text-gray-600">Variação de impressões</p><p className="mt-2 text-2xl font-bold text-red-700">{data.impressionsChange}</p><p className="mt-1 text-xs text-gray-500">vs. período anterior</p></div><div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-xs font-semibold text-gray-600">Variação de CTR</p><p className="mt-2 text-2xl font-bold text-red-700">{data.ctrChange}</p><p className="mt-1 text-xs text-gray-500">de {data.ctrPrevious.toLocaleString('pt-BR', { minimumFractionDigits: 1 })}% para {data.ctr.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}%</p></div><div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-xs font-semibold text-gray-600">Variação de posição</p><p className="mt-2 text-2xl font-bold text-red-700">{data.avgPositionChange}</p><p className="mt-1 text-xs text-gray-500">de {data.avgPositionPrevious.toLocaleString('pt-BR', { minimumFractionDigits: 1 })} para {data.avgPosition.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</p></div></div>
    <div className="executive-takeaway mb-8"><p className="executive-takeaway-label">Leitura executiva</p><p className="text-lg font-semibold leading-relaxed text-[#203c50]">A coleta registrou 18 cliques, 4.010 impressões, CTR de 0,45% e posição média de 9,63. Em relação ao período anterior, todos os quatro indicadores apresentaram variação desfavorável.</p></div>
    <div className="card-premium mb-8"><h3 className="section-subtitle">Desempenho diário retornado</h3><p className="mb-5 text-xs text-gray-500">A fonte retornou dados somente para 02/09 a 06/09. Os dias sem retorno não foram preenchidos.</p><ResponsiveContainer width="100%" height={300}><ComposedChart data={data.dailyMetrics} margin={{ top: 8, right: 16, left: -12, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e5e5e5" /><XAxis dataKey="date" stroke="#74808a" fontSize={12} /><YAxis yAxisId="left" stroke="#74808a" fontSize={12} /><YAxis yAxisId="right" orientation="right" stroke="#74808a" fontSize={12} /><Tooltip contentStyle={{ backgroundColor: '#fff', border: '1px solid #dfe6ea', borderRadius: '10px' }} /><Bar yAxisId="left" dataKey="impressions" fill="#203c50" radius={[6, 6, 0, 0]} name="Impressões" /><Line yAxisId="right" type="monotone" dataKey="clicks" stroke="#ff6737" strokeWidth={3} dot={{ fill: '#ff6737', r: 4 }} name="Cliques" /></ComposedChart></ResponsiveContainer></div>
    <div className="mb-8 grid grid-cols-1 gap-8 lg:grid-cols-2"><div className="card-premium"><h3 className="section-subtitle">Consultas principais</h3><div className="overflow-x-auto"><table className="w-full min-w-[590px] text-left text-sm"><thead className="border-b border-gray-200 text-xs uppercase tracking-wide text-gray-500"><tr><th className="pb-3 font-semibold">Consulta</th><th className="pb-3 text-right font-semibold">Cliques</th><th className="pb-3 text-right font-semibold">Impressões</th><th className="pb-3 text-right font-semibold">Posição</th></tr></thead><tbody>{data.queries.map((query) => <tr key={query.query} className="border-b border-gray-100 last:border-0"><td className="py-3 pr-3 font-medium text-[#203c50]">{query.query}</td><td className="py-3 text-right font-bold text-[#ff6737]">{query.clicks ?? '—'}</td><td className="py-3 text-right text-gray-700">{query.impressions}</td><td className="py-3 text-right text-gray-700">{query.position.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</td></tr>)}</tbody></table></div></div><div className="card-premium"><h3 className="section-subtitle">Conteúdos principais</h3><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b border-gray-200 text-xs uppercase tracking-wide text-gray-500"><tr><th className="pb-3 font-semibold">Conteúdo</th><th className="pb-3 text-right font-semibold">Cliques</th><th className="pb-3 text-right font-semibold">Impressões</th></tr></thead><tbody>{data.contents.map((content) => <tr key={content.title} className="border-b border-gray-100 last:border-0"><td className="py-3 pr-3 font-medium text-[#203c50]">{content.title}</td><td className="py-3 text-right font-bold text-[#ff6737]">{content.clicks}</td><td className="py-3 text-right text-gray-700">{content.impressions}</td></tr>)}</tbody></table></div></div></div>
  </div></section>;
}
